// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuarantineConvo.Data;

namespace QuarantineConvo.Migrations
{
    [DbContext(typeof(QuarantineConvoContext))]
    [Migration("20200406162102_UpdateConnectionDB")]
    partial class UpdateConnectionDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuarantineConvo.Models.Connection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConnectionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<int?>("user1ID")
                        .HasColumnType("int");

                    b.Property<int?>("user2ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("user1ID");

                    b.HasIndex("user2ID");

                    b.ToTable("Connection");
                });

            modelBuilder.Entity("QuarantineConvo.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QuarantineConvo.Models.Connection", b =>
                {
                    b.HasOne("QuarantineConvo.Models.User", "user1")
                        .WithMany()
                        .HasForeignKey("user1ID");

                    b.HasOne("QuarantineConvo.Models.User", "user2")
                        .WithMany()
                        .HasForeignKey("user2ID");
                });
#pragma warning restore 612, 618
        }
    }
}
